### PR TITLE
Add polygon draw controls to geomap

### PR DESCRIPTION
**Pull request by stefanprobst**
this adds a component for polygon selection on maps, and refactors some of the data massaging on geomap pages.

changes from https://github.com/InTaVia/web/tree/feat/vq-place-constraint-widget can be applied on top if we want a circle selection tool instead.

### CODE REVIEW

**Comment by stefanprobst** [comment]
trying to figure out how to render initial geojson features with `draw`.

the following complains about an empty store:

```js
useControl(
  ({ map }) => {
    const draw = new MapboxDraw(props);

    function addInitialFeatures() {
      if (initialFeatures != null) {
        initialFeatures.forEach((feature) => {
          draw.add(feature);
        });
      }
    }

    map.on("load", addInitialFeatures);

    return draw;
  }
);
```

**Comment by stefanprobst** [comment]
probably can only add features once the control has been added to the map?

**Comment by stefanprobst** [comment]
ok, working now, ready for review

**Comment by johannesliem** [comment]
While validation on github did not work at the time, local valiation did pass.

**Pull request merged**
